export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_SINGLE_CATEGORY_REQUEST = "GET_SINGLE_CATEGORY_REQUEST";
export const GET_SINGLE_CATEGORY_SUCCESS = "GET_SINGLE_CATEGORY_SUCCESS";
export const GET_SINGLE_CATEGORY_FAILURE = "GET_SINGLE_CATEGORY_FAILURE";

export const GET_MORE_IMAGES_REQUEST = "GET_MORE_IMAGES_REQUEST";
export const GET_MORE_IMAGES_SUCCESS = "GET_MORE_IMAGES_SUCCESS";
export const GET_MORE_IMAGES_FAILURE = "GET_MORE_IMAGES_FAILURE";